name: ✦☠︎𝕰𝖛𝖎𝖑 𝕹~𝕸~𝕷♫⃝✙.
services:
  - name: ✦☠︎𝕰𝖛𝖎𝖑 𝕹~𝕸~𝕷♫⃝✙.-service
    type: web
    ports:
      - 5000
    routes:
      - path: "/"
    build:
      type: docker
      dockerfile: ./Dockerfile
    regions:
      - fra
      - sin
      
